version: '3'

services:
  mongodb:
    image: mongo:6.0
    container_name: chatroom-sellia
    ports:
      - "27017:27017"
    # volumes:
    #   - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
